### ISSUE TITLE
Adding Pre-Raid BiS for Each Class

### ISSUE THREAD

**Issue by Chzconey** [Warkdev/BestInSlotClassic#13]
Add a Pre-Raid BiS and where to get them.

**Comment by Warkdev** [comment]
Hello,

Thank you for proposing so. I've 2 comments however:
- Pre-raid BIS are already available if you uncheck the "Raid checkbox", you'll only see items that are accessible out of raids.
- This issue is always a reference to add "Source of the items": https://github.com/Warkdev/BestInSlotClassic/issues/2

Can I then close this one ?

Wark
