### ISSUE TITLE
Hit cap

### ISSUE THREAD

**Issue by pandoux** [Warkdev/BestInSlotClassic#30]
Hi guys :)

First, thanks for your job :)

Second, all is in the title 👍 :)
Is it possible to integrate the possibility to optimize the BiS with/without/in progress hitcap ?

Thanks a lot :)

**Comment by Warkdev** [comment]
Hello,

Thanks for the feedback :)

What's hit cap for you ? How would you see that ? I wanted to add main stats at some points but I've found addons able to do that pretty nicely (that I'm personally using): https://www.curseforge.com/wow/addons/characterstatsclassic

Wark

**Comment by pandoux** [comment]
Some of stuff have good stats, but if i follow your addon, i don't have my hit or touch cap :)
Explications : [https://fr.wowhead.com/news=292085/hit-cap-in-classic-wow-clarifications](url)

For peoples, BiS is the best template of stuff that they can have.
But, it's not correct if i refered to your addon.
For exemple, if you havn't your hit cap, you can miss some knocks.
And the best in slot is finaly : hit cap 9% > First stat > Second Stat.

In real, it's realy complicated for some class to have 9% to hit but we can't be stong without it :)
In tank role, if i havn't my hit cap, i can miss my taunt and the boss can go away ^^'

**My feeling :** 
Actualy i have 7% and it's not perfect but acceptable.

**My proposition :** 
Add a feature like a cursor (0% to 9%) and propose equipements with this restriction. 

Thanks

**Comment by Warkdev** [comment]
That's over-complex for the add-on which has already difficulties to handle it this way :)

Thank you for your suggestion. Regarding the bis list for warriors, it's coming from this: https://docs.google.com/spreadsheets/d/1YXJpasqqodeq9B4jeUZDP9khFQf5QocyMby6moydJWk/htmlview?usp=sharing#

As you can see, there are meaningful comments that you should be aware of before trusting the TOP1 of each BIS slot. Having edgemasters is, for instance, lowering the hit cap to 6% rather than 9%. This is a huge gap. The addon is taking this into account :)

Wark

**Comment by Warkdev** [comment]
Hello,

Can I close this issue or you have something else to add? ☺️

Wark
